### ISSUE TITLE
Problems opening project

### ISSUE THREAD

**Issue by ehedlin** [drebain/CSC305_GLSL_Lecture#1]
Im getting an error when I try to open the project

![capture d ecran 2018-02-13 a 11 13 53 am](https://user-images.githubusercontent.com/23744775/36168878-63d52458-10af-11e8-87a2-f5800319fbf3.png)

**Comment by drebain** [comment]
It seems that the CMake file for finding dependencies that I used does not work with your machine (Assuming you have the dependencies, GLFW, GLEW, etc.). If you can build the code in the [icg repo](https://github.com/ArthurFirmino/icg), then try adding the apps directory from this repo to your icg folder and adding each app subdirectory to the root CMakeLists.txt there.

**Comment by ehedlin** [comment]
worked perfectly. thank you
